
import Head from 'next/head';
import Layout from './../src/components/client/layout/index';


export default function Home() {

  return (
    <>
      <Head>
        <title>Scounted</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        
      </Layout>
    </>
  );
}

export async function getServerSideProps() {

  return {
    props: {
      
    }
  }
}
